@baseUrl =  http://localhost:3000

### AppControllerGatHello

# @name AppControllerGatHello
GET {{baseUrl}}/


### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/exemplo

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico