@baseUrl =  http://localhost:3000

# RECADOS
###
GET {{baseUrl}}/recados/
###
GET {{baseUrl}}/recados/12
###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "recado": "Este e o recado que estou enviando",
    "nova chave": "outro valor"
}


### AppControllerGatHello

# @name AppControllerGatHello
GET {{baseUrl}}/


### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/exemplo

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico